---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fron-back
  name: fron-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fron-back
  template:
    metadata:
      labels:
        app: fron-back
    spec:
      containers:
        - image: kirillkaragodin/frontend:1.0.0
          name: frontend
          ports:
            - containerPort: 80
          env:
            - name: BASE_URL
              value: http://localhost:9000
        - image: kirillkaragodin/backend:1.0.0
          name: backend
          env:
            - name: DATABASE_URL
              value: postgres://postgres:postgres@postgres.stage.svc.cluster.local:5432/news
          ports:
            - containerPort: 9000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: fron-back
  name: fron-back
spec:
  ports:
    - name: "fron-back"
      port: 30000
      targetPort: 80
  selector:
    app: fron-back
  type: ClusterIP
